ALTER TABLE `Integration`
  MODIFY `provider` ENUM('HUBSPOT', 'SALESFORCE', 'SHOPIFY', 'WOOCOMMERCE', 'SQUARE', 'PIPEDRIVE', 'CSV') NOT NULL;

ALTER TABLE `ExternalContactRecord`
  MODIFY `provider` ENUM('HUBSPOT', 'SALESFORCE', 'SHOPIFY', 'WOOCOMMERCE', 'SQUARE', 'PIPEDRIVE', 'CSV') NOT NULL;

ALTER TABLE `ExternalEvent`
  MODIFY `provider` ENUM('HUBSPOT', 'SALESFORCE', 'SHOPIFY', 'WOOCOMMERCE', 'SQUARE', 'PIPEDRIVE', 'CSV') NOT NULL;
