/** One-time asset build. Run from repo root:
 * pnpm --filter server exec tsx scripts/generateStarterAdImages.ts
 *
 * Renders the hand-authored icon fixtures in scripts/fixtures/starter-icons/ to transparent PNGs
 * via the same Playwright capture session the catalog previews themselves use, then writes the
 * result as base64 data URI constants into packages/ad-renderer/src/starterImages.ts. Baked in at
 * build time, not fetched at request time — createStarterAds() stays a pure function with no
 * network/browser dependency, and general Asset upload never needs to support raw SVG (a real
 * XSS surface for user-uploaded files) just to ship these 7 illustrations.
 */
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { openAdCreativeCaptureSession } from '../src/lib/adCreativeCapture'

const ICON_SIZE = 600
const FIXTURES_DIR = resolve(import.meta.dirname, 'fixtures/starter-icons')
const OUTPUT_FILE = resolve(
  import.meta.dirname,
  '../../../packages/ad-renderer/src/starterImages.ts',
)

async function main() {
  const files = (await readdir(FIXTURES_DIR)).filter((f) => f.endsWith('.svg')).sort()
  const session = await openAdCreativeCaptureSession()
  const entries: { key: string; base64: string }[] = []
  try {
    for (const file of files) {
      const svg = await readFile(resolve(FIXTURES_DIR, file), 'utf8')
      const html = `<!doctype html><html><head><style>html,body{margin:0;background:transparent}</style></head><body>${svg}</body></html>`
      const shot = await session.capture(
        html,
        { width: ICON_SIZE, height: ICON_SIZE },
        { omitBackground: true },
      )
      const key = file.replace(/\.svg$/, '')
      entries.push({ key, base64: shot.buffer.toString('base64') })
      console.log(`${key}: ${shot.widthPx}×${shot.heightPx}, ${shot.buffer.length} bytes`)
    }
  } finally {
    await session.close()
  }

  const body = entries
    .map(({ key, base64 }) => `  ${key}: 'data:image/png;base64,${base64}',`)
    .join('\n')
  const source = `// Generated by apps/server/scripts/generateStarterAdImages.ts from
// apps/server/scripts/fixtures/starter-icons/*.svg — do not hand-edit. Re-run the script to
// regenerate after changing a fixture. Keyed by AdPurpose (minus 'blank', which never carries a
// starter image).
export const STARTER_AD_IMAGES: Record<string, string> = {
${body}
}
`
  await writeFile(OUTPUT_FILE, source)
  console.log(`Wrote ${OUTPUT_FILE}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
