import { db } from '@project/db'

export class CommissionEngine {
  /**
   * Process a membership payment and generate any corresponding affiliate earnings.
   * Based on the BusinessAffiliateAttribution snapshot at the time of processing.
   */
  async processMembershipPayment(
    businessId: string,
    amountMinor: number,
    overrides?: {
      stripeInvoiceId?: string
      stripeChargeId?: string
    },
  ) {
    return await db.$transaction(async (tx) => {
      // 0. Check for idempotency
      if (overrides?.stripeInvoiceId || overrides?.stripeChargeId) {
        const existing = await tx.membershipPayment.findFirst({
          where: {
            OR: [
              { stripeInvoiceId: overrides.stripeInvoiceId || undefined },
              { stripeChargeId: overrides.stripeChargeId || undefined },
            ],
            businessId,
          },
        })
        if (existing) return existing
      }

      // 1. Record the payment
      const payment = await tx.membershipPayment.create({
        data: {
          businessId,
          amountMinor,
          stripeInvoiceId: overrides?.stripeInvoiceId,
          stripeChargeId: overrides?.stripeChargeId,
        },
      })

      // 2. Lookup attribution
      const attribution = await tx.businessAffiliateAttribution.findUnique({
        where: { businessId },
      })

      if (!attribution) return payment

      // 3. Calculate Direct Commission
      const directAmountMinor = Math.round((amountMinor * attribution.affiliateRateBps) / 10000)

      if (directAmountMinor > 0) {
        await tx.platformAffiliateEarning.create({
          data: {
            membershipPaymentId: payment.id,
            beneficiaryAffiliateId: attribution.affiliateId,
            sourceAffiliateId: attribution.affiliateId, // direct sale
            type: 'DIRECT',
            baseAmountMinor: amountMinor,
            rateBps: attribution.affiliateRateBps,
            amountMinor: directAmountMinor,
            status: 'PENDING',
          },
        })

        // 4. Calculate Manager Override (if applicable)
        if (attribution.managerAffiliateId && attribution.managerShareBps) {
          const managerAmountMinor = Math.round(
            (directAmountMinor * attribution.managerShareBps) / 10000,
          )
          if (managerAmountMinor > 0) {
            await tx.platformAffiliateEarning.create({
              data: {
                membershipPaymentId: payment.id,
                beneficiaryAffiliateId: attribution.managerAffiliateId,
                sourceAffiliateId: attribution.affiliateId, // generated by this affiliate's sale
                type: 'MANAGER_OVERRIDE',
                baseAmountMinor: directAmountMinor, // override is applied to the direct commission amount
                rateBps: attribution.managerShareBps,
                amountMinor: managerAmountMinor,
                status: 'PENDING',
              },
            })
          }
        }
      }

      return payment
    })
  }

  /**
   * Reverse a membership payment and its associated earnings without mutating historical amounts.
   */
  async reverseMembershipPayment(paymentId: string) {
    return await db.$transaction(async (tx) => {
      // Find the original earnings associated with this payment
      const earnings = await tx.platformAffiliateEarning.findMany({
        where: { membershipPaymentId: paymentId, status: { not: 'REVERSED' } },
      })

      for (const earning of earnings) {
        if (earning.status === 'PENDING') {
          // If still pending, we can simply mark it as reversed
          await tx.platformAffiliateEarning.update({
            where: { id: earning.id },
            data: { status: 'REVERSED' },
          })
        } else {
          // If already PAYABLE or PAID, preserve original status and append an offsetting negative line item
          // The negative line item is PAYABLE so it deducts from their next payout
          await tx.platformAffiliateEarning.create({
            data: {
              membershipPaymentId: earning.membershipPaymentId,
              beneficiaryAffiliateId: earning.beneficiaryAffiliateId,
              sourceAffiliateId: earning.sourceAffiliateId,
              type: earning.type,
              baseAmountMinor: -earning.baseAmountMinor,
              rateBps: earning.rateBps,
              amountMinor: -earning.amountMinor,
              status: 'PAYABLE',
              reversesEarningId: earning.id,
            },
          })
        }
      }
    })
  }

  /**
   * Mark earnings as payable after any refund window or clearing period has passed.
   */
  async markPayable(earningIds: string[]) {
    await db.platformAffiliateEarning.updateMany({
      where: {
        id: { in: earningIds },
        status: 'PENDING',
      },
      data: {
        status: 'PAYABLE',
      },
    })
  }
}
