import { db } from '@project/db'
import type { GoalRecurrenceRule, ScheduledGoal } from '@prisma/client'

// Recurrence (2026-09-15 Calendar connective-tissue pass) — deliberately NOT completion-
// triggered. See ScheduledGoal.recurrenceRule's own schema comment for the full rationale: the
// poller keeps at most one *future* instance of a series materialized at all times, generating the
// next one the moment the current one's own scheduledFor arrives, regardless of its status. A
// series is every ScheduledGoal sharing one recurrenceGroupId; the poller only ever looks at each
// series' latest (by scheduledFor) instance.
function computeNextOccurrence(current: Date, rule: GoalRecurrenceRule): Date {
  const next = new Date(current)
  switch (rule) {
    case 'DAILY':
      next.setUTCDate(next.getUTCDate() + 1)
      return next
    case 'WEEKLY':
      next.setUTCDate(next.getUTCDate() + 7)
      return next
    case 'MONTHLY':
      next.setUTCMonth(next.getUTCMonth() + 1)
      return next
    case 'WEEKDAYS':
      do {
        next.setUTCDate(next.getUTCDate() + 1)
      } while (next.getUTCDay() === 0 || next.getUTCDay() === 6)
      return next
  }
}

export async function runDueRecurringGoals(): Promise<{ created: number }> {
  const latestPerGroup = await db.scheduledGoal.groupBy({
    by: ['recurrenceGroupId'],
    where: { recurrenceGroupId: { not: null } },
    _max: { scheduledFor: true },
  })

  let created = 0
  for (const group of latestPerGroup) {
    const groupId = group.recurrenceGroupId
    const maxScheduledFor = group._max.scheduledFor
    if (!groupId || !maxScheduledFor) continue

    // Ties (a concurrent-create race landed two rows at the same instant) resolve to the most
    // recently created — deterministic, and the externalKey idempotency guard below makes a
    // slightly-wrong pick here harmless either way.
    const latest: ScheduledGoal | null = await db.scheduledGoal.findFirst({
      where: { recurrenceGroupId: groupId, scheduledFor: maxScheduledFor },
      orderBy: { createdAt: 'desc' },
    })
    // Repeats was turned off on the latest instance (recurrenceRule -> null) — this is the whole
    // series-cancellation mechanism, see the schema comment. Nothing to do.
    if (!latest || !latest.recurrenceRule || !latest.scheduledFor) continue
    // Still in the future — only ever keep one future instance materialized.
    if (latest.scheduledFor > new Date()) continue

    const nextDate = computeNextOccurrence(latest.scheduledFor, latest.recurrenceRule)
    if (latest.recurrenceEndDate && nextDate > latest.recurrenceEndDate) continue

    // Deterministic per series+day — reuses the same externalKey uniqueness CRM_NEXT_ACTION
    // already relies on, so a concurrent/overlapping tick can never double-generate.
    const externalKey = `recurring:${groupId}:${nextDate.toISOString().slice(0, 10)}`
    try {
      await db.$transaction(async (tx) => {
        const next = await tx.scheduledGoal.create({
          data: {
            businessId: latest.businessId,
            externalKey,
            title: latest.title,
            detail: latest.detail,
            notes: latest.notes,
            source: latest.source,
            sourceTemplateId: latest.sourceTemplateId,
            assistantGoalCycleId: latest.assistantGoalCycleId,
            createdByUserId: latest.createdByUserId,
            assignedToUserId: latest.assignedToUserId,
            subjectType: latest.subjectType,
            subjectId: latest.subjectId,
            actionType: latest.actionType,
            actionTarget: latest.actionTarget,
            actionLabel: latest.actionLabel,
            trackingType: 'MANUAL',
            estimateMinutes: latest.estimateMinutes,
            scheduledFor: nextDate,
            hasTime: latest.hasTime,
            status: 'SCHEDULED',
            recurrenceRule: latest.recurrenceRule,
            recurrenceGroupId: latest.recurrenceGroupId,
            recurrenceEndDate: latest.recurrenceEndDate,
          },
        })
        await tx.goalEvent.create({ data: { goalId: next.id, type: 'CREATED' } })
        await tx.goalEvent.create({ data: { goalId: next.id, type: 'SCHEDULED' } })
      })
      created++
    } catch (err: unknown) {
      if ((err as { code?: string } | null)?.code === 'P2002') continue // generated by a concurrent tick
      console.error(
        `[RecurringGoal] Failed to generate next occurrence for series ${groupId}:`,
        err,
      )
    }
  }
  return { created }
}
